### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by jmlongriver** [markus-eberts/spert#5]
For json file, I noticed that sounds likely all the sentences have entities and relations, wonder if we need to keep those sentences without relations or entities?

**Comment by markus-eberts** [comment]
I assume you refer to the SciERC dataset since there are no samples without entities+relations in the other two datasets. We simply converted the original dataset (see reference below) into a different format.

```
Yi Luan, Luheng He, Mari Ostendorf, and Hannaneh Hajishirzi, ‘Multi-Task Identification of Entities, Relations, and Coreference for Scientific Knowledge Graph Construction’, in Proc. of EMNLP 2018, pp. 3219–3232, Brussels, Belgium, (October-November 2018). ACL.
```

Because the original dataset contains sentences without entities and relations, you should also include those sentences if you want a 1:1 comparison with previous work. If you don't want to compare to previous work (or want to use an other/your own dataset), it still can make sense to include sentences without entities+relations for negative sampling.

**Comment by jmlongriver** [comment]
That makes sense, so  I want to include sentence without entities and relations, what format should I convert to?  are the program still able to handle that kind of format?

Thanks

**Comment by markus-eberts** [comment]
Yes, you can have a look at the format of the datasets located in 'data/datasets' (after executing './scripts/fetch_datasets.sh'). It should work as long as your dataset is in the same format. 

In case a sample does not contain any entity or relation, just leave the 'entities' or 'relations' list in the corresponding sample empty.
